apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kube-secrets-exporter-crb
  labels:
    app: kube-secrets-exporter
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kube-secrets-exporter-cr
subjects:
  - kind: ServiceAccount
    name: kube-secrets-exporter-sa
    namespace: monitoring
