apiVersion: v1
kind: Service
metadata:
  name: kube-secrets-exporter
  namespace: monitoring
  labels:
    app: kube-secrets-exporter
spec:
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: kube-secrets-exporter
