apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: kube-secrets-exporter
  namespace: monitoring
  labels:
    release: kube-secrets-exporter
spec:
  selector:
    matchLabels:
      app: kube-secrets-exporter
  endpoints:
    - port: http
      interval: 30s
      path: /metrics
